fix getting origin default branch

diff --git a/prebuild-flow/action.yml b/prebuild-flow/action.yml
--- a/prebuild-flow/action.yml
+++ b/prebuild-flow/action.yml
@@ -21,11 +21,11 @@ runs:
       with:
         fetch-depth: 0 # required to fetch main
     - id: check_merged_main
-      name: Check if tag is merged into main
+      name: Check if tag is merged into ${{ github.event.repository.default_branch }}
       if: startsWith(github.ref, 'refs/tags/')
       run: |
-        if ! git merge-base --is-ancestor ${{ github.ref }} origin/HEAD; then
-          echo "This tag is not merged into $(git rev-parse --abbrev-ref origin/HEAD). Aborting build."
+        if ! git merge-base --is-ancestor ${{ github.ref }} origin/${{ github.event.repository.default_branch }}; then
+          echo "This tag is not merged into ${{ github.event.repository.default_branch }}. Aborting build."
           exit 1
         fi
       shell: bash
